### ISSUE TITLE
Lightbeam for Android

### ISSUE THREAD

**Issue by istiaqueahamed** [mozilla/lightbeam#667] opened 2015-02-10 07:01 UTC
I can not find Lightbeam for Android version. How can I use lightbeam in a Android.

**Comment by kbrosnan** [comment] 2015-02-10 07:05
This is a duplicate of issue 450.

**Comment by istiaqueahamed** [comment] 2015-02-10 07:12
I am extremly sorry about that.... please apologise to me.

**Closed** 2015-02-10 21:07 UTC
