### ISSUE TITLE
merge nodes/sites

### ISSUE THREAD

**Issue by unchartedxx** [mozilla/lightbeam#95] opened 2012-08-05 23:13 UTC
Wish: It would be a good idea to merge sites we know are connected, like youtube and google, or amazon.com and amazon.co.uk. It can be automatic using an hardcoded list or using a button on the UI.

**Comment by fmarier** [comment] 2015-02-13 02:06
Duplicate of #608.

**Closed by fmarier** 2015-02-13 02:06 UTC
Labels: Design Feedback Requested, Visualization Ideas
