### ISSUE TITLE
Lightbeam!!!

### ISSUE THREAD

**Issue by pristinumCCIV** [mozilla/lightbeam#722] opened 2017-03-12 20:50 UTC
There is No icon shown as the instuctions says. The icon just isn't there. So I cannot open Lightbeam, good-bye!!

**Comment by fmarier** [comment] 2017-03-22 17:48
I assume this is a duplicate of #720 and that it will be fixed in 1.3.2.

**Closed by fmarier** 2017-03-22 17:48 UTC
